"""empty message

Revision ID: b1dc1deaada0
Revises: 4b0a0dc719e6
Create Date: 2020-04-27 23:09:35.702753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1dc1deaada0'
down_revision = '4b0a0dc719e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'latitude',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('users', 'longitude',
               existing_type=sa.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'longitude',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('users', 'latitude',
               existing_type=sa.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###
